title: Upstream - Without A Paddle
description: >- 
  This site is a chronicle of my home lab and Kubernetes hobby.  
  It includes periodic Blog posts about random topics, as well as tutorials focused on cloud native technologies.  
  Topics covered include Quarkus, OpenShift, OKD, Tekton, MariaDB, Cassandra, Infrastructure As Code, and much more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://upstreamwithoutapaddle.com" 
github_username:  cgruver
theme: minima
# theme: jekyll-theme-cayman
header_pages:
 - pages/main/lab-projects.md
 - pages/main/videos.md
 - pages/main/about.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
minima:
  social_links:
    github: cgruver
    twitter: upstreampaddle
