# theme: minimal-mistakes
minimal_mistakes_skin: "dirt"
locale: "en-US"
title: "Upstream - Without A Paddle"
subtitle: "OpenShift is Kubernetes + Fun"
name: cgruver
description: >
  This site is a chronicle of my home lab and Kubernetes hobby.  
  It includes periodic Blog posts about random topics, as well as tutorials focused on cloud native technologies.  
  Topics covered include Quarkus, OpenShift, OKD, Tekton, MariaDB, Cassandra, Infrastructure As Code, and much more.
url: "https://upstreamwithoutapaddle.com"
baseurl: ""
repository: "cgruver/cgruver"
logo: "/assets/images/logo.jpg"
twitter:
  username: upstreampaddle
author:
  name: "cgruver"
  avatar: /assets/images/Avatar.jpeg
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://upstreamwithoutapaddle.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/upstreampaddle"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cgruver"
footer:
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://upstreamwithoutapaddle.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/upstreampaddle"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cgruver"
sass:
  sass_dir: _sass
  style: compressed
include:
 - _pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      classes: wide
      show_date: true
      sidebar:
        nav: lab-projects
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: false
      classes: wide
      sidebar:
        nav: lab-projects
paginate: 10
paginate_path: /page:num/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - customization/
